stages:
  - test
  - build
  - test2
  - dev
  - stage
  - prod 

install_env:
  stage: test
  sccript: 
    - echo " 1 test ..............."

run_test:
  stage: test
  sccript:
    - echo " 2 test ..............."

install_env:
  stage: test
  sccript:
    - echo "  test liner..............."

build:
  stage: build
  script:
    - echo 'running ./build.sh'

total_after_buildd:
  stage: test2
  script: 
    - echo "test after build 1 ............."

deploy_dev:
  stage: dev
  script: 
    - echo 'running ./build.sh'

deploy_stage:
  stage: stage
  script:
    - echo 'running ./build.sh'
  when: manual

deploy_prod:
  stage: prod
  script: 
    - echo 'running ./build.sh'
  when: manual
  only:
    refs:
      - tags
      - main


